const subjects=[
 {id:'mtk',name:'Matematika',icon:'🔢',desc:'Bilangan, pecahan, geometri, pengukuran, data dan operasi hitung.'},
 {id:'bi',name:'Bahasa Indonesia',icon:'📖',desc:'Teks, ide pokok, informasi, pidato, iklan, surat dan literasi.'},
 {id:'pancasila',name:'Pendidikan Pancasila',icon:'🇮🇩',desc:'Pancasila, norma, hak-kewajiban, persatuan dan keberagaman.'},
 {id:'sbdp',name:'SBDP',icon:'🎨',desc:'Seni rupa, musik, tari, prakarya dan budaya daerah.'},
 {id:'ipas',name:'IPAS',icon:'🔬',desc:'Makhluk hidup, energi, bumi, lingkungan, kesehatan dan masyarakat.'},
 {id:'inggris',name:'Bahasa Inggris',icon:'🇬🇧',desc:'Vocabulary, daily expressions, reading, writing dan simple grammar.'},
 {id:'coding',name:'Koding',icon:'💻',desc:'Algoritma, berpikir komputasional, pola, urutan dan pemrograman dasar.'}
];
const materialMap={
 mtk:['Operasi Bilangan Bulat dan Pecahan','Perbandingan dan Skala','Bangun Ruang dan Volume','Data dan Penyajian Data'],
 bi:['Ide Pokok dan Informasi Penting','Teks Eksplanasi','Pidato Persuasif','Surat dan Iklan'],
 pancasila:['Nilai-Nilai Pancasila','Hak dan Kewajiban','Persatuan dalam Keberagaman','Musyawarah'],
 sbdp:['Seni Rupa: Poster','Musik dan Lagu Daerah','Tari Tradisional Gayo','Prakarya dan Budaya Lokal'],
 ipas:['Sistem Peredaran Darah','Energi dan Perubahannya','Tata Surya','Pelestarian Lingkungan'],
 inggris:['Greetings and Introductions','Daily Activities','Describing People and Places','Simple Past Tense'],
 coding:['Algoritma dan Urutan','Pola dan Abstraksi','Percabangan','Proyek Coding Sederhana']
};
const key='edukelas6_data';
let data=JSON.parse(localStorage.getItem(key)||'null')||{school:'SD Negeri 2 Dabun Gelang',teacher:'',semester:'Ganjil',activities:[]};
function save(){localStorage.setItem(key,JSON.stringify(data));}
function subject(id){return subjects.find(s=>s.id===id)}
function render(page='dashboard'){
 document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page===page));
 const app=document.getElementById('app');
 if(page==='dashboard')app.innerHTML=dashboard();
 if(page==='materi')app.innerHTML=materi();
 if(page==='kegiatan')app.innerHTML=formActivity();
 if(page==='laporan')app.innerHTML=laporan();
 if(page==='pengaturan')app.innerHTML=pengaturan();
 bind(page);
}
function dashboard(){return `<section class="hero"><div><div class="pill">Aplikasi Pembelajaran Digital</div><h1>EduKelas VI</h1><p>Kelola materi, kegiatan pembelajaran, asesmen, dan laporan kelas dalam satu aplikasi.</p></div><div class="hero-badge">Kelas VI<br><small>SD</small></div></section><div class="section-title"><h2>Ringkasan</h2></div><div class="report-summary"><div class="card"><div class="muted">Kegiatan tercatat</div><div class="stat">${data.activities.length}</div></div><div class="card"><div class="muted">Mata pelajaran</div><div class="stat">7</div></div><div class="card"><div class="muted">Materi tersedia</div><div class="stat">${Object.values(materialMap).flat().length}</div></div><div class="card"><div class="muted">Semester</div><div class="stat" style="font-size:20px">${data.semester}</div></div></div><div class="section-title"><h2>Mata Pelajaran</h2><button class="primary" onclick="render('kegiatan')">+ Catat Kegiatan</button></div><div class="grid">${subjects.map(s=>`<div class="card subject material" onclick="openMaterial('${s.id}')"><div class="icon">${s.icon}</div><h3>${s.name}</h3><p class="muted">${s.desc}</p><span class="pill">${materialMap[s.id].length} materi</span></div>`).join('')}</div>`}
function materi(){return `<div class="section-title"><div><h1>📚 Materi Pembelajaran</h1><p class="muted">Materi terintegrasi untuk Kelas VI SD.</p></div></div><div class="grid">${subjects.map(s=>`<div class="card"><h3>${s.icon} ${s.name}</h3>${materialMap[s.id].map((m,i)=>`<div style="padding:10px 0;border-bottom:1px solid #edf1ee"><b>${i+1}. ${m}</b><br><small class="muted">Tujuan: memahami konsep dan menerapkannya dalam konteks kehidupan sehari-hari.</small></div>`).join('')}</div>`).join('')}</div>`}
function formActivity(){return `<div class="section-title"><div><h1>📝 Catat Kegiatan Pembelajaran</h1><p class="muted">Setiap data tersimpan otomatis di perangkat ini.</p></div></div><div class="panel"><form id="activityForm"><div class="form-grid"><label>Tanggal<input name="date" type="date" value="${new Date().toISOString().slice(0,10)}" required></label><label>Mata Pelajaran<select name="subject" required>${subjects.map(s=>`<option value="${s.id}">${s.name}</option>`).join('')}</select></label><label class="full">Materi<select name="material" id="materialSelect"></select></label><label>Metode Pembelajaran<select name="method"><option>Diskusi</option><option>Problem Based Learning</option><option>Project Based Learning</option><option>Eksperimen</option><option>Demonstrasi</option><option>Literasi</option><option>Praktik</option></select></label><label>Asesmen<select name="assessment"><option>Observasi</option><option>Penugasan</option><option>Kuis</option><option>Proyek</option><option>Tes tertulis</option><option>Unjuk kerja</option></select></label><label>Jumlah Siswa<input name="students" type="number" min="0" value="0"></label><label>Rata-rata Nilai<input name="score" type="number" min="0" max="100" value="0"></label><label class="full">Catatan / Refleksi<textarea name="notes" placeholder="Tuliskan aktivitas, ketercapaian, kendala dan tindak lanjut..."></textarea></label></div><div class="actions"><button class="primary" type="submit">💾 Simpan Kegiatan</button><button class="ghost" type="reset">Reset</button></div></form></div>`}
function laporan(){let total=data.activities.length,avg=total?Math.round(data.activities.reduce((a,x)=>a+Number(x.score||0),0)/total):0;return `<div class="section-title"><div><h1>📊 Laporan Pembelajaran</h1><p class="muted">Rekap kegiatan yang sudah disimpan.</p></div><button class="primary" id="downloadBtn2">⬇️ Download CSV</button></div><div class="report-summary"><div class="card"><div class="muted">Total kegiatan</div><div class="stat">${total}</div></div><div class="card"><div class="muted">Rata-rata nilai</div><div class="stat">${avg}</div></div><div class="card"><div class="muted">Guru</div><div class="stat" style="font-size:17px">${data.teacher||'-'}</div></div><div class="card"><div class="muted">Sekolah</div><div style="font-weight:700">${data.school}</div></div></div><div class="panel table-wrap"><table><thead><tr><th>Tanggal</th><th>Mapel</th><th>Materi</th><th>Metode</th><th>Siswa</th><th>Nilai</th><th>Catatan</th><th></th></tr></thead><tbody>${data.activities.length?data.activities.map((x,i)=>`<tr><td>${x.date}</td><td>${subject(x.subject)?.name||x.subject}</td><td>${x.material}</td><td>${x.method}</td><td>${x.students}</td><td>${x.score}</td><td>${x.notes||'-'}</td><td><button class="danger" onclick="removeActivity(${i})">Hapus</button></td></tr>`).join(''):`<tr><td colspan="8" class="empty">Belum ada kegiatan. Silakan catat kegiatan pembelajaran.</td></tr>`}</tbody></table></div>`}
function pengaturan(){return `<div class="section-title"><div><h1>⚙️ Pengaturan</h1><p class="muted">Identitas laporan dan data aplikasi.</p></div></div><div class="panel"><form id="settingsForm"><div class="form-grid"><label>Nama Sekolah<input name="school" value="${data.school}"></label><label>Nama Guru<input name="teacher" value="${data.teacher}" placeholder="Nama guru"></label><label>Semester<select name="semester"><option ${data.semester==='Ganjil'?'selected':''}>Ganjil</option><option ${data.semester==='Genap'?'selected':''}>Genap</option></select></label></div><div class="actions"><button class="primary">Simpan Pengaturan</button><button type="button" class="danger" id="clearData">Hapus Semua Data</button></div></form></div><div class="panel notice"><b>Catatan:</b> data aplikasi disimpan di browser (localStorage). Untuk penggunaan bersama banyak perangkat, aplikasi dapat dikembangkan berikutnya dengan database seperti Supabase/Firebase.</div>`}
function bind(page){if(page==='kegiatan'){const f=document.getElementById('activityForm');const s=f.subject,m=f.material;function fill(){m.innerHTML=materialMap[s.value].map(x=>`<option>${x}</option>`).join('')}s.addEventListener('change',fill);fill();f.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(f);data.activities.unshift(Object.fromEntries(fd));save();alert('Kegiatan berhasil disimpan.');render('laporan')})}if(page==='laporan')document.getElementById('downloadBtn2')?.addEventListener('click',downloadCSV);if(page==='pengaturan'){document.getElementById('settingsForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.target);data.school=fd.get('school');data.teacher=fd.get('teacher');data.semester=fd.get('semester');save();alert('Pengaturan tersimpan.');render('dashboard')});document.getElementById('clearData').addEventListener('click',()=>{if(confirm('Hapus semua kegiatan?')){data.activities=[];save();render('laporan')}})}}
function openMaterial(id){const s=subject(id);const modal=document.createElement('div');modal.className='modal';modal.innerHTML=`<div class="modal-box"><button class="close" onclick="this.closest('.modal').remove()">×</button><h2>${s.icon} ${s.name}</h2><p>${s.desc}</p><h3>Materi Kelas VI</h3><ol>${materialMap[id].map(x=>`<li style="padding:8px">${x}</li>`).join('')}</ol><button class="primary" onclick="this.closest('.modal').remove();render('kegiatan');setTimeout(()=>document.querySelector('[name=subject]').value='${id}',50)">Catat kegiatan dari mapel ini</button></div>`;document.body.appendChild(modal)}
function removeActivity(i){if(confirm('Hapus kegiatan ini?')){data.activities.splice(i,1);save();render('laporan')}}
function csvEscape(v){return '"'+String(v??'').replaceAll('"','""')+'"'}
function downloadCSV(){const headers=['Tanggal','Mata Pelajaran','Materi','Metode','Asesmen','Jumlah Siswa','Rata-rata Nilai','Catatan'];const rows=data.activities.map(x=>[x.date,subject(x.subject)?.name||x.subject,x.material,x.method,x.assessment,x.students,x.score,x.notes]);const csv='\ufeff'+[headers,...rows].map(r=>r.map(csvEscape).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='Laporan_Pembelajaran_Kelas_VI.csv';a.click();URL.revokeObjectURL(a.href)}
document.addEventListener('click',e=>{const n=e.target.closest('.nav');if(n)render(n.dataset.page)});document.getElementById('downloadBtn').addEventListener('click',downloadCSV);document.getElementById('printBtn').addEventListener('click',()=>window.print());render();